export const Type = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  CLEAR_BASKET: "CLEAR_BASKET",
  SET_USER:"SET_USER",
};
